name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 */12 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACCOUNT_new: ${{secrets.ACCOUNT_new}}
          PASSWORD_new: ${{secrets.PASSWORD_new}}
          ACC_HELP0: ${{ secrets.ACC_HELP0 }}
          PASS_HELP0: ${{ secrets.PASS_HELP0 }}
          ACC_HELP1: ${{ secrets.ACC_HELP1 }}
          PASS_HELP1: ${{ secrets.PASS_HELP1 }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD}
          python3 clock-in.py ${ACCOUNT_new} ${PASSWORD_new}
          python3 clock-in.py ${ACC_HELP0} ${PASS_HELP0}
          python3 clock-in.py ${ACC_HELP1} ${PASS_HELP1}
